// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwSuGuvTBXYnDVoxgC9qBze29fHOt27rw',
    appId: '1:523660262535:web:c0f712b23beed2a9a78c22',
    messagingSenderId: '523660262535',
    projectId: 'fokkkus',
    authDomain: 'fokkkus.firebaseapp.com',
    storageBucket: 'fokkkus.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbTahm__MsxgVRWPGpoGo-TQQj7oth4Pw',
    appId: '1:523660262535:android:d5d21e620b9b7c58a78c22',
    messagingSenderId: '523660262535',
    projectId: 'fokkkus',
    storageBucket: 'fokkkus.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0tvTZGAddRssikcHUzt0dHInaE2xWb78',
    appId: '1:523660262535:ios:416aff93ad0fcc19a78c22',
    messagingSenderId: '523660262535',
    projectId: 'fokkkus',
    storageBucket: 'fokkkus.appspot.com',
    iosBundleId: 'com.example.fokkkus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0tvTZGAddRssikcHUzt0dHInaE2xWb78',
    appId: '1:523660262535:ios:f52c35b06687d9b1a78c22',
    messagingSenderId: '523660262535',
    projectId: 'fokkkus',
    storageBucket: 'fokkkus.appspot.com',
    iosBundleId: 'com.example.fokkkus.RunnerTests',
  );
}
